---
- hosts: all
  become: true
  tasks:  
  - name: Install dependencies packages for docker-ce
    apt:
      name: "{{ packages }}"
      state: present
      install_recommends: false
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  handlers:
    - name: docker status
      service: name=docker state=started    

- hosts: swarm-master-1
  become: true

  tasks:
    - name: Initialize the cluster
      shell: docker swarm init --advertise-addr {{ node_ip }} >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt    

    - name: Get master join command
      shell: docker swarm join-token manager
      register: master_join_command

    - name: Copy master join command to local file
      become: no
      local_action: copy content="{{ master_join_command.stdout_lines[2] }}" dest="master-join-command.sh"

    - name: Get worker join command
      shell: docker swarm join-token worker
      register: worker_join_command

    - name: Copy worker join command to local file
      become: no
      local_action: copy content="{{ worker_join_command.stdout_lines[2] }}" dest="worker-join-command.sh"

- hosts: swarm-master-2
  become: true

  tasks:
  - name: Copy the master join command to server location
    copy: src=master-join-command.sh dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

- hosts: swarm-worker-1 swarm-worker-2 swarm-worker-3 swarm-worker-4
  become: true

  tasks:
  - name: Copy the mster join command to server location
    copy: src=worker-join-command.sh dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh                        